### ISSUE TITLE
Add in rank heatmap

### ISSUE THREAD

**Issue by mortonjt** [biocore/rhapsody#53]
This can help allow for diagnostics for posterior distributions of the resulting ranks.

**Comment by nbokulich** [comment]
Hey Jamie I am interested in this issue, could you assign to me?

Just to make sure we are on the same page, do you have any sample images of how you would like this plot to look?

**Comment by mortonjt** [comment]
Thanks @nbokulich !

There are 2 types of heatmaps that are used in the paper.

Heatmap of the conditional probabilities (below)

![image](https://user-images.githubusercontent.com/4184797/61834240-fb08de80-ae2b-11e9-83f0-f60c662316cb.png)

This was just using seaborn, highlighting some of the microbes of interest.  The challenge here will be to figure out the minimal functionality to expose to users (i.e. probably don't want to enable filtering / sorting in the first pass).

Paired heatmap to show matched microbes to metabolites.  The right figure are the abundances of 2 microbes across samples, the left figure is the top 50 metabolites for each of these microbes across samples.

![image](https://user-images.githubusercontent.com/4184797/61834232-f47a6700-ae2b-11e9-9719-8b0987a8f009.png)

This will be harder to pull off, since it may require more interactively (but would be great, because this is very tedious to put together manually).
